package etherlandscore.etherlandscore.fibers;

public enum MasterCommand {
  context_create_gamer,
  context_save_all,
  team_remove_gamer,
  team_create_team,
  gamer_add_friend,
  district_reclaim_district,
  gamer_link_address,
  gamer_remove_friend,
  group_add_gamer,
  group_remove_gamer,
  group_set_priority,
  team_create_group,
  team_delete_group,
  team_create_district,
  team_delete_district,
  team_delegate_district,
  district_set_group_permission,
  district_set_gamer_permission,
  team_delete_team,
  team_add_gamer,
  map_create_map,
  map_render_maps,
  nft_create_nft,
  context_process_gamer_transaction,
  context_mint_tokens,
  gamer_toggle_message,
  touch_district, touch_gamer, shop_create_shop
}
