package etherlandscore.etherlandscore.fibers;

public enum MasterCommand {
  context_create_gamer,
  context_save_all,
  town_remove_gamer,
  town_create_town,
  gamer_add_friend,
  district_reclaim_district,
  gamer_link_address,
  gamer_remove_friend,
  team_add_gamer,
  team_remove_gamer,
  team_set_priority,
  town_create_team,
  town_delete_team,
  town_create_district,
  town_delete_district,
  town_delegate_district,
  district_set_team_permission,
  district_set_gamer_permission,
  town_delete_town,
  town_add_gamer,
  map_create_map,
  map_render_maps,
  nft_create_nft,
  context_process_gamer_transaction,
  context_mint_tokens,
  gamer_toggle_message,
  touch_district, touch_gamer, shop_create_shop,
  context_store_captcha, store_gamer_location
}
