package etherlandscore.etherlandscore.fibers;

public enum MasterCommand {
  context_create_gamer,
  context_save_all,
  team_remove_gamer,
  team_create_team,
  gamer_add_friend,
  plot_set_owner,
  district_set_priority,
  district_remove_plot,
  district_add_plot,
  gamer_link_address,
  plot_update_plot,
  gamer_remove_friend,
  group_add_gamer,
  group_remove_gamer,
  group_set_priority,
  team_create_group,
  team_delete_group,
  team_create_district,
  team_delete_district,
  team_delegate_plot,
  plot_reclaim_plot,
  district_set_group_permission,
  district_set_gamer_permission,
  team_delete_team,
  team_add_gamer,
  map_create_map,
  nft_create_nft
}
